lib/config/routes.rb
Rails.application.routes.draw do

  get 'login/signup_new'

  get 'login/signup_create'

  root 'login#new'

  get 'books/search_form'
  get 'books/search'
  get 'books/add_new_book'
  get 'books/add_new_book_form'
  get 'books/admin_reserve_initiate'
  get 'books/prompt_user_id'
  get 'books/update'
  get 'books/suggest_new_book_form'
  get 'books/suggest_new_book'
  get 'books/suggestions_index'
  get 'books/edit_suggestion_details_form'
  get 'books/delete_suggestion'
  get 'books/show_waitlist'

  resources :books
  get 'users/view_members'

  match ':controller(/:action(/:id))', :via => [ :get, :post, :patch]

end

lib/app/models/book.rb
class Book < ActiveRecord::Base

  # validation check columns
  validates :isbn, presence: true, uniqueness: true
  validates :name, presence: true
  validates :authors, presence: true
  validates :status, presence: true

  # Relationships
  has_many :reservations
  has_many :users, through: :waitlists
  enum status: [:available, :checkedOut]
end

lib/app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_filter :user_logged_in?

  # GET /books
  def index
    @books = Book.where('isDeleted = FALSE')
    # Admin
    if session[:role] & User::IS_ADMIN > 0
      render 'admin_book_catalog'
    else
      render 'members_book_catalog'
    end
  end

  # GET /books/1
  def show
    @book = Book.find(params[:id])
    @waitlist = Waitlist.where(user_id: session[:user_id], book_id: @book.id)
    if session[:role] & User::IS_ADMIN > 0
      render 'admin_show_view'
    else
      render 'member_show_view'
    end
  end

  # GET /books/1/edit
  def edit
    logger.debug "Into books#edit : Received this id : #{params[:id]}"
    @book = Book.find(params[:id])
  end

  # PATCH/PUT /books/1
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to @book, notice: 'Book was successfully updated.'
    else
      flash[:notice] = "There was an error in updating the book details"
      render :edit
    end
  end

  # DELETE /books/1
  def destroy
    @book = Book.find(params[:id])
    # See if there are any active reservations
    reservations = Reservation.where('book_id = ? and dateReturned IS NULL', @book.id)
    if reservations[0]
      flash[:notice] = "There are active check-outs for this book"
    else
      @book.update(isDeleted: TRUE)
      flash[:notice] = " Book : #{@book.name} successfully deleted"
    end
    redirect_to action: 'index'
  end

  # New methods
  def reserve
    logger.debug "Into reserve"
    book = Book.find(params[:id])
    user = User.where('email = ?', session[:email])
    # puts book.status
    if book.status == 'available'
      reservation = Reservation.new(user_id: user[0].id, book_id: book.id, dateIssued: Time.now.getutc);
      if reservation.save(validate: true)
        book.update(:status => :checkedOut)
        flash[:notice] = "Book titled #{book.name} successfully checked out"
      else
        flash[:notice] = "There was an error in checking out the book requested."
      end
    else
      flash[:notice] = "The book is not available in the library. It is already checked out."
    end

    # Redirect back to the book catalog
    redirect_to action: 'index'
  end

  def admin_reserve_initiate
    logger.debug "Into admin_reserve_initiate: params hash : #{params.inspect}"
    flash[:book_id] = params[:id]
    redirect_to action: 'prompt_user_id'
  end

  # A stub for "on behalf" form
  def prompt_user_id
  end

  def admin_reserve
    # puts params[:id]
    # puts params[:email]
    users = User.where('email = ? AND isDeleted = FALSE', params[:email])
    book = Book.find(params[:id])
    if users[0]
      if users[0].role & User::IS_MEMBER > 0
        # We can go ahead with the reservation
        if book.status == 'available'
          reservation = Reservation.new(user_id: users[0].id, book_id: book.id, dateIssued: Time.now.getutc);
          if reservation.save(validate: true)
            book.update(:status => :checkedOut)
            flash[:notice] = "Book #{book.name} successfully checked out to #{users[0].name}."
          else
            flash[:notice] = "There was an error in checking out the book requested."
          end
        else
          flash[:notice] = "The book is not available in the library. It is already checked out."
        end
      else
        flash[:notice] = "User is not a valid library member"
      end
    else
      flash[:notice] = "Member does not exist"
    end
    redirect_to action:'index'
  end

  def search_form
    @book = Book.new
  end

  def search
    # puts params[:status]
    if params[:status]=='Available'
      status = 0
    else
      status = 1
    end
    @books = Book.where("(name LIKE ? OR authors LIKE ? OR description LIKE ? OR isbn LIKE ?) AND status=?","%#{params[:search_string]}%", "%#{params[:search_string]}%", "%#{params[:search_string]}%", "%#{params[:search_string]}%", status)
  end

  def add_new_book_form
    @book = Book.new
  end

  def add_new_book
    # puts "In add_new_book"
    input = book_params
    @book = Book.new(name: input[:name], authors: input[:authors], description: input[:description], isbn: input[:isbn], status: :available)
    if @book.save
      flash[:notice] = "Book : #{@book.name} is successfully added"
    else
      flash[:notice] = "There was an error in adding the book to the catalog."
    end
    redirect_to action: 'index'
  end

  def suggestions_index
    @suggestions = BookSuggestion.all

    if session[:role] & User::IS_ADMIN > 0
      render 'admin_suggestions_index'
    else
      render 'member_suggestions_index'
    end
  end

  def suggest_new_book_form
    @suggestion = BookSuggestion.new

  end

  def suggest_new_book
    suggestion = BookSuggestion.new(book_params)
    if suggestion.save
      flash[:notice] = "Book : #{suggestion.name} is successfully added as a suggestion."
    else
      flash[:notice] = "There was an error in adding the book to the suggestions list."
    end
    redirect_to action: 'suggestions_index'
  end

  def edit_suggestion_details_form
    @book = BookSuggestion.find(params[:id])
  end

  def edit_suggestion_details
  end

  def delete_suggestion

    @book = BookSuggestion.find(params[:id])
    if @book.destroy
      flash[:notice] = "Book Suggestion #{@book.name} successfully deleted"
    else
      flash[:notice] = "There was an error in deleting the book suggestion : #{@book.name}"
    end
    redirect_to action: 'suggestions_index'

  end

  def add_to_catalog
    addBooks = BookSuggestion.where(id: params[:id])
    addBooks.each do |suggestion|
      # book = Book.new(name: suggestion.name, isbn: isbn, authors: suggestion.authors, description: suggestion.description, status: :available)
      book = Book.new(name: params[:book][:name], isbn: params[:book][:isbn], authors: params[:book][:authors], description: params[:book][:description], status: :available)
      if book.save!
        suggestion.destroy
        flash[:notice] = "Book : #{params[:book][:name]} successfully added to the book catalog"
      else
        flash[:notice] = "There was an error in adding this book : #{params[:book][:name]} to the catalog"
      end
    end
    redirect_to action: 'suggestions_index'
  end


  def checkout_history
    @checkout_history  = Reservation.select("reservations.*,users.*").
                              where(book_id: params[:id]).
                              joins("JOIN users ON reservations.user_id=users.id").order(dateIssued: :desc)
    @book = Book.select(:name,:authors,:isbn, :id).where(id: params[:id])
  end


  def addWaitlist
    waitlist_new = Waitlist.new(user_id: session[:user_id],book_id:params[:id])
    if waitlist_new.save(validate: true)
      flash[:notice] = "You have been added to waitlist"
    end
    @book = Book.find(params[:id])
    @waitlist = waitlist_new.id
    render('member_show_view')
  end

  def show_waitlist
    @waitlists = Waitlist.joins(:user, :book).order(book_id: :asc, created_at: :asc)
  end

  private

    # Only allow a trusted parameter "white list" through.
    def book_params
      params.require(:book).permit(:name, :isbn, :authors, :description)
    end

    def user_signed_in
      session[:email] != nil
    end
end

lib/app/helpers/books_helper.rb
module BooksHelper
end

lib/app/views/books/_check_signed_in.erb
<% if !session[:email] %>
    Not authorized to view this page
<%end%>

lib/app/views/books/add_new_book_form.erb
<h1> Add new Book </h1>
<%= form_tag action: 'add_new_book' do %>
    <%= render 'form' %> <br>
    <%= submit_tag "Add"%>
<%end%>
<br><br>
<%= render 'footer' %>

lib/app/views/books/admin_book_catalog.html.erb
<h1>Books Catalog</h1>

<p id="notice"><%= notice %></p>

<table class="tables">
  <thead>
  <tr>
    <th> Book Name</th>
  </tr>
  </thead>

  <tbody>
  <% @books.each do |book| %>
      <tr>
        <td> <%= book.name %> </td>
        <td><%= link_to 'View Details', book %></td>
        <td><%= link_to 'Edit Details', edit_book_path(book) %></td>
        <td><%= link_to 'Delete' , book, method: :delete, data: { confirm: 'Are you sure?' }%></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= button_to 'Add a new book', controller: 'books', action: 'add_new_book_form' %>
<br>
<%= button_to 'Suggest a new book', controller: 'books', action: 'suggest_new_book_form' %>
<br> <br>

<%= render 'footer'%>

lib/app/views/books/admin_show_view.html.erb
<p id="notice"><%= notice %></p>

<table class = "tables">
  <tr>
    <td> Book Name</td>
    <td> <b> <%= @book.name %></b></td>
  </tr>

  <tr>
    <td> ISBN</td>
    <td> <b> <%= @book.isbn %></b></td>
  </tr>

  <tr>
    <td> Author(s)</td>
    <td> <b> <%= @book.authors %></b></td>
  </tr>

  <tr>
    <td> Book Description</td>
    <td> <b> <%= @book.description %></b></td>
  </tr>

  <tr>
    <td> Status </td>
    <td> <b><%if @book.status=='available' %>
          Available
          <%else%>
          Checked Out
          <%end%>
    </b></td>
  </tr>
</table>
<!-- If an admin, show up the Edit functionality -->
<!-- Checkout button -->
<br> <br>

<% if @book.status=='available' %>
    <%= button_to "Checkout", { action: 'admin_reserve_initiate', id: @book.id }, method: :post, data: { confirm: "Are you sure?" } %>
    <% else %>
    <%= button_to "Checkout", { action: 'admin_reserve_initiate', id: @book.id }, { method: :post, disabled: :true} %>
<%end%>
<br> <br>
<%= button_to "Checkout History", { action: 'checkout_history', id: @book.id }, { method: :post} %>
<br> <br>

<%= link_to 'Edit Details', edit_book_path(@book) %><br>
<%= link_to 'Back', books_path %>
<br> <br>
<%= render 'footer'%>

lib/app/views/books/checkout_history.html.erb
<h1>Checkout History</h1>
<p>ISBN: <%= @book[0].isbn %></p>
<p><%= @book[0].name %> by <%= @book[0].authors %></p>

<table class="tables">
  <tr>
    <th>User Id</th>
    <th>User Name</th>
    <th>Email</th>
    <th>Date Issued</th>
    <th>Date Returned</th>
  </tr>
  <% @checkout_history.each do |m|%>
      <tr>
        <td><%= m.user_id %></td>
        <td><%= m.name %></td>
        <td><%= m.email %></td>
        <td><%= m.dateIssued %></td>
        <td>
          <% if !m.dateReturned %>
              <%= link_to 'return', {:controller => 'users', :action => 'return', :book_id => m.book_id, :user_id => m.user_id} %>
          <%else%>
              <%= m.dateReturned %>
          <%end%>
        </td>
      </tr>
  <% end %>
</table>

<%= render 'books/footer'%>

lib/app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= flash[:notice] %>

<%= form_tag books_update_path do %>
    <%= render 'form' %>
    <%= hidden_field_tag :id , @book.id %>
    <br>
    <%= submit_tag "Update" %>
<%end%>
<br>
<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

<br>
<br>
<%= render 'footer' %>

lib/app/views/books/edit_suggestion_details_form.html.erb
<h1> Edit Suggestion Details </h1>
<%= form_tag action: 'add_to_catalog', id: @book do %>
    <%= render 'form' %> <br>
    <%= submit_tag "Add"%>
<%end%>
<br><br>
<%= render 'footer' %>

lib/app/views/books/member_suggestions_index.html.erb
<h1>Book Suggestions</h1>

<p id="notice"><%= notice %></p>

<% if @suggestions.count > 0 %>
    <table class="tables">
      <thead>
      <tr>
        <th> Book Name</th>
        <th> Author(s)</th>
      </tr>
      </thead>

      <tbody>
      <% @suggestions.each do |suggestion| %>
          <tr>
            <td> <%= suggestion.name %> </td>
            <td> <%= suggestion.authors %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <% else %>
        <b> There are currently no book suggestions</b>
    <% end %>
<br> <br>

<%= render 'footer'%>

lib/app/views/books/members_book_catalog.html.erb
<p id="notice"><%= notice %></p>

<h1>Books Catalog</h1>

<table class="tables">
  <thead>
  <tr>
    <th colspan="3"> Books</th>
  </tr>
  </thead>

  <tbody>
  <% @books.each do |book| %>
      <tr>
        <td> <%= book.name %> </td>
        <td><%= link_to 'View Details', book %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= button_to 'Search', controller: 'books', action: 'search_form' %>
<br>
<%= button_to 'Suggest a new book', controller: 'books', action: 'suggest_new_book_form' %>

<br> <br>
<%= render 'footer'%>

lib/app/views/books/not_authorized.html.erb
<h3> Not Authorized to view this page</h3>

lib/app/views/books/prompt_user_id.html.erb
<%=form_tag controller: 'books', action: 'admin_reserve' do %>
    <tr>
      <th> <%= label_tag :email, "Enter the member's email ID " %></th>
      <th> <%= text_field_tag(:email)%></th>
    </tr>

    <%= hidden_field_tag :id , flash[:book_id] %>
    <br> <br>
    <%= submit_tag "Confirm" %>
<%end%>
<br> <br>
<%= render 'footer' %>

lib/app/views/books/search.html.erb
<h1>Search Results</h1>
<% if @books.count > 0 %>
    <table class="tables">
      <thead>
      <tr>
        <th> Book ISBN</th>
        <th> Name</th>
        <th> Authors</th>
        <th> Description</th>
        <th> Status</th>
      </tr>
      </thead>

      <tbody>
      <% @books.each do |book| %>
          <tr>
            <td> <%= book.isbn %> </td>
            <td> <%= book.name %> </td>
            <td> <%= book.authors %></td>
            <td> <%= book.description %></td>
            <td> <%if book.status == 'available' %> Available
                  <% else%> Checked Out <%end%></td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% else %>
  Your search criteria returned no results<br><br>
<% end %>

<%= link_to "New Search", controller: 'books', action: 'search_form' %>
<br> <br>
<%= render 'footer' %>

lib/app/views/books/show_waitlist.html.erb
<table class="tables">
  <% if @waitlists.count > 0 %>
  <thead>
  <tr>
    <th> Book Name</th>
    <th> Waiting Number</th>
    <th> Created At </th>
    <th> Member email</th>
    <th> Member Name </th>
  <tbody>

  <%waiting_number = 1
     curr_book = ""
     prev_book = "" %>
  <% @waitlists.each do |entry| %>
      <tr>
        <% curr_book = entry.book.name
        if curr_book != prev_book
            prev_book = curr_book
            waiting_number = 1
        else
            waiting_number = waiting_number + 1
        end%>

        <td> <%= entry.book.name %> </td>
        <td> W/L <%= waiting_number %></td>
        <td><%= entry.created_at %></td>
        <td><%= entry.user.email%></td>
        <td><%= entry.user.name %></td>
      </tr>
  <% end %>
  </tbody>
</table>

  <% else %>
      There are no users currently waiting on any book.
  <%end%>
<br>
<br>

<%= render 'footer' %>

lib/app/views/books/suggest_new_book_form.html.erb
<h1> Add new Book Suggestion </h1>
<%= form_tag action: 'suggest_new_book' do %>
    <table class="tables">

      <tr>
        <th> <%= label_tag(:name)%></th>
        <th> <%= text_field(:book, :name, required: :true)%></th>
      </tr>

      <tr>
        <th> <%= label_tag(:isbn)%></th>
        <th> <%= text_field(:book, :isbn)%></th>
      </tr>

      <tr>
        <th> <%= label_tag(:authors)%></th>
        <th> <%= text_field(:book, :authors, required: :true)%></th>
      </tr>

      <tr>
        <th> <%= label_tag(:description)%></th>
        <th> <%= text_field(:book, :description)%></th>
      </tr>

    </table>
    <br>
    <%= submit_tag "Add Suggestion"%>
<%end%>
<br><br>
<%= render 'footer' %>